# -*- mode: python -*-
% Regression tests for Scapy NDN regarding NdnLenField and NdnTypeField

############
############
+ Tests on NDN basic fields

= Ndn Length Field tests

from scapyndn.pkt import \
    NdnLenField, NameComponent, Sha256Digest, TYPES, COMP_TYPES, \
    Interest, Name, Nonce, DoubleNameComponent, \
    NonNegIntNameComponent, VersionNameComponent

# Empty
assert NdnLenField().addfield(Raw(""), b"\x08", None) == b"\x08"
assert NdnLenField().addfield(None, b"", None) == b""

# Already defined length
assert NdnLenField().addfield(None, b"", 8) == b"\x08"

# Length of value="test" is 4
assert NdnLenField().addfield(Raw("test"), b"\x08", None) == b"\x08\x04"
# NameComponent contains the type and length fields which should be skipped when calculating length
assert NdnLenField().addfield(NameComponent(value="test"), b"\x08", None) == b"\x08\x04"

p = "test" * 1000
assert NdnLenField().addfield(Raw(p), b"\x08", None) == b"\x08\xfd\x0f\xa0"

q = "test" * 100000
assert NdnLenField().addfield(Raw(q), b"\x08", None) == b"\x08\xfe\x00\x06\x1a\x80"

# Takes time to run:
# r = "test" * 2000000000
# assert NdnLenField().addfield(Raw(r), b"\x08", None) == b'\x08\xff\x00\x00\x00\x01\xdc\xd6\x50\x00'

assert NdnLenField().getfield(None, b"") == (b"", None)
assert NdnLenField().getfield(None, b"\x04test") == (b"test", 4)

# Technically illegal packet - but someone should be able to form
assert NdnLenField().getfield(None, b"\x04tes") == (b"tes", 4)
assert NdnLenField().getfield(None, b"\xfd\x0f\xa0" + p.encode('ascii')) == (p.encode('ascii'), 4000)
assert NdnLenField().getfield(None, b"\xfe\x00\x06\x1a\x80" + q.encode('ascii')) == (q.encode('ascii'), 400000)
# Test w/o value - too slow/resource intensive
# assert NdnLenField().getfield(None, b"\xff\x00\x00\x00\x01\xdc\xd6\x50\x00") == ("", 8000000000)


= Name Component tests

nc = NameComponent(value="ndn-cxx")
nc.type
assert nc.type == TYPES['GenericNameComponent']
# Not calculated yet
assert nc.length == None
assert nc.value == b"ndn-cxx"

rnc = raw(nc)
bnc = NameComponent(rnc)
assert bnc.length == 0x7
assert len(nc) == 9
assert rnc == b"\x08\x07\x6E\x64\x6E\x2D\x63\x78\x78"

nc = NameComponent(type=140, value="ndn-cxx")
assert nc.type == 140

# Test NameComponent field boundaries/padding according to length
nc = NameComponent(b"\x08\x07\x6E\x64\x6E\x2D\x63\x78\x78\x00\x00")
assert raw(nc.payload) == b"\x00\x00"

# Non negative integer test
for item in [ (20, 1, b"\x14"), (4500, 2, b"\x11\x94"), (70000, 4, b"\x00\x01\x11\x70"),
              (4294967296, 8, b"\x00\x00\x00\x01\x00\x00\x00\x00") ]:
    nc = NonNegIntNameComponent(raw(NonNegIntNameComponent(value=item[0])))
    #print(nc.value)
    #nc.show2()
    assert nc.type == TYPES['GenericNameComponent']
    assert nc.length == item[1]
    assert nc.value == item[0]

# Similar to v=20
nc = VersionNameComponent(value=20)
rnc = raw(nc)
bnc = VersionNameComponent(rnc)
assert bnc.type == COMP_TYPES["v"]
assert rnc == b"\x36\x01\x14"

nc = Sha256Digest(value="28bad4b5275bd392dbb670c75cf0b66f13f7942b21e80f55c0e86b374753a548")
rnc = raw(nc)
bnc = Sha256Digest(rnc)
assert bnc.type == COMP_TYPES["sha256digest"]

= Double Name Component Tests

nc = DoubleNameComponent(value=21.359888375)
rnc = raw(nc)
bnc = DoubleNameComponent(rnc)
assert bnc.type == TYPES["GenericNameComponent"]
assert bnc.length == 8
assert bnc.value == 21.359888375
assert rnc == b"\x08\x08\x40\x35\x5C\x21\xA5\x00\xD5\xE9"

nc = DoubleNameComponent(b"\x08\x08\x40\x35\x5C\x21\xA5\x00\xD5\xE9\x00")
assert "Padding" in nc

nc = NameComponent(rnc)
assert nc.to_double() == 21.359888375
